model_params:
  hidden_layers:
  - 128
  - 128
  - 128
  input_dim: 5
  output_dim: 3
paths:
  base_save_dir: trained_models
  csv_path: /home/nexus/VQ_PMCnmpc/VQ_PMC/logs/datasets/dataset_random.csv
training_params:
  batch_size: 64
  epochs: 20
  learning_rate: 0.0001
  val_split: 0.3
