model_params:
  hidden_layers:
  - 256
  - 256
  - 256
  - 256
  p_dropout: 0.0
paths:
  base_save_dir: trained_models
  csv_path: /home/nexus/VQ_PMCnmpc/VQ_PMC/logs/datasets/dataset_nmpc.csv
training_params:
  batch_size: 64
  epochs: 500
  history_length: 3
  learning_rate: 1.0e-05
  val_split: 0.3
